# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swatchify < Formula
  desc "Extract dominant colors from images"
  homepage "https://github.com/james-see/swatchify"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/swatchify/releases/download/v0.3.0/swatchify_0.3.0_darwin_amd64.tar.gz"
      sha256 "a2856167d2c58a4792db7f60e7e462e26ade6eaed365c89b43a457d2dc695afe"

      def install
        bin.install "swatchify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/swatchify/releases/download/v0.3.0/swatchify_0.3.0_darwin_arm64.tar.gz"
      sha256 "09c2a5e2840f84537efc0ffb714d25e3fb028e2794dbcb33e192816955758981"

      def install
        bin.install "swatchify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/swatchify/releases/download/v0.3.0/swatchify_0.3.0_linux_amd64.tar.gz"
      sha256 "685e43c00e37f3a6f24d3dd63590301eed31524f7eab0ea0d39debd84f7a87b9"
      def install
        bin.install "swatchify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/swatchify/releases/download/v0.3.0/swatchify_0.3.0_linux_arm64.tar.gz"
      sha256 "0bec587895abe375d293eb05e8277d9710a3df01ea91613d54fa7be362fac5ed"
      def install
        bin.install "swatchify"
      end
    end
  end
end
