# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swatchify < Formula
  desc "Extract dominant colors from images"
  homepage "https://github.com/james-see/swatchify"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/swatchify/releases/download/v0.4.0/swatchify_0.4.0_darwin_amd64.tar.gz"
      sha256 "b7e35e0969ed8e9c6ffd39a05eff3931b6600c229c94edb1fc878f9b7059909b"

      define_method(:install) do
        bin.install "swatchify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/swatchify/releases/download/v0.4.0/swatchify_0.4.0_darwin_arm64.tar.gz"
      sha256 "e9b7b0d3d9ce12aa9d11b2172b6f85fe9ca9fd3112f3b023164746c81d145669"

      define_method(:install) do
        bin.install "swatchify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/swatchify/releases/download/v0.4.0/swatchify_0.4.0_linux_amd64.tar.gz"
      sha256 "9c90f6baae633d9c3f0e8e62842a5e1e4a3f2f306a4bc2161fa13d04cf8a5b3c"
      define_method(:install) do
        bin.install "swatchify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/swatchify/releases/download/v0.4.0/swatchify_0.4.0_linux_arm64.tar.gz"
      sha256 "d4284188094542daebaa0c5ff79b5721447149bbf05294d35e6e7a41982b2dfd"
      define_method(:install) do
        bin.install "swatchify"
      end
    end
  end
end
