# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindadomain < Formula
  desc "Domain availability checker with TUI - Go find a domain!"
  homepage "https://github.com/james-see/gofindadomain"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.2/gofindadomain_1.0.2_darwin_amd64.tar.gz"
      sha256 "f7d1c5cd4dd2d6cb8bd6d1646b3e5bf7e462125041c9aa17e6ec6a203b4f2e44"

      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.2/gofindadomain_1.0.2_darwin_arm64.tar.gz"
      sha256 "c2bcfa9be534a2b658c073959e7d0e30a81c9cfdd97543d2609ec07d9adeb1cf"

      def install
        bin.install "gofindadomain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.2/gofindadomain_1.0.2_linux_amd64.tar.gz"
      sha256 "dd84aee85617c27476490e16fc979044f9ba21a536eb41fabc5c5a4efbe122a6"
      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.2/gofindadomain_1.0.2_linux_arm64.tar.gz"
      sha256 "eeb541253f183136068d7de15d8d8d5cf546eec5d6a6905d0c5ec1165866bad3"
      def install
        bin.install "gofindadomain"
      end
    end
  end

  test do
    system "#{bin}/gofindadomain", "--help"
  end
end
