# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindadomain < Formula
  desc "Domain availability checker with TUI - Go find a domain!"
  homepage "https://github.com/james-see/gofindadomain"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.1/gofindadomain_1.0.1_darwin_amd64.tar.gz"
      sha256 "ca725c7fac486ba94949a628f9abd1c08e23ebcf0058f9b400f8f521ed79e3b6"

      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.1/gofindadomain_1.0.1_darwin_arm64.tar.gz"
      sha256 "5df70af99c12d461d9a4c6f248f737e0cb1b41fa135700abdd1b6c1a23273490"

      def install
        bin.install "gofindadomain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.1/gofindadomain_1.0.1_linux_amd64.tar.gz"
      sha256 "8f2d946d2d86ba1a16e0e32d9444a4bd23660499385b9f67813ea61a90b33771"
      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.1/gofindadomain_1.0.1_linux_arm64.tar.gz"
      sha256 "8fc26855c8a3af9a2d8e2fdac6e48fd6b79eb1589b73a3096e773abeb62cb06b"
      def install
        bin.install "gofindadomain"
      end
    end
  end

  test do
    system "#{bin}/gofindadomain", "--help"
  end
end
