# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindpi < Formula
  desc "Fast network device scanner with manufacturer identification"
  homepage "https://github.com/james-see/gofindpi"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/gofindpi/releases/download/v2.0.0/gofindpi_2.0.0_darwin_amd64.tar.gz"
      sha256 "f74f61f879901f059796d10af8e15c21d24b12c4101a3334e9b6a884e5c17293"

      def install
        bin.install "gofindpi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/gofindpi/releases/download/v2.0.0/gofindpi_2.0.0_darwin_arm64.tar.gz"
      sha256 "dc15b6a2e991851d0b72b49a72776a2d2a7d20a9620e92acdcd7f211825025b2"

      def install
        bin.install "gofindpi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindpi/releases/download/v2.0.0/gofindpi_2.0.0_linux_amd64.tar.gz"
      sha256 "54981326c0ce5c9844f8e1f912bf700ada3877b274e0561e7a8dd3a42cdf8c95"
      def install
        bin.install "gofindpi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindpi/releases/download/v2.0.0/gofindpi_2.0.0_linux_arm64.tar.gz"
      sha256 "c65fcb3015719ec24a3146ad4af2b57add205b2520bb4c663d23d890ae48044a"
      def install
        bin.install "gofindpi"
      end
    end
  end

  test do
    system "#{bin}/gofindpi", "--version"
  end
end
