# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindadomain < Formula
  desc "Domain availability checker with TUI - Go find a domain!"
  homepage "https://github.com/james-see/gofindadomain"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.3/gofindadomain_1.0.3_darwin_amd64.tar.gz"
      sha256 "fbcf1ba9545fdd19298ada6932f8d510524f24bb38a1eafff5e6bbce23c01836"

      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.3/gofindadomain_1.0.3_darwin_arm64.tar.gz"
      sha256 "778c3cdfae50c82568b213e74397049317e154928f6d95e514b35fd0b2f2c9cf"

      def install
        bin.install "gofindadomain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.3/gofindadomain_1.0.3_linux_amd64.tar.gz"
      sha256 "6b6a9d1f5a808f67e28320186a6493f5b100213b9ba4a94131816c93d900b626"
      def install
        bin.install "gofindadomain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/gofindadomain/releases/download/v1.0.3/gofindadomain_1.0.3_linux_arm64.tar.gz"
      sha256 "b27434976ed4170c4e68b70a0531a6a902c83777b0e068c4c3eebc86fe063c7e"
      def install
        bin.install "gofindadomain"
      end
    end
  end

  test do
    system "#{bin}/gofindadomain", "--help"
  end
end
