# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synthtribe2midi < Formula
  desc "Convert between MIDI and Behringer SynthTribe formats"
  homepage "https://james-see.github.io/synthtribe2midi"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.0/synthtribe2midi_Darwin_x86_64.tar.gz"
      sha256 "d8593def9c7e859721d2ed860578f00e38d0a49e288984e837aa629edf50de66"

      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.0/synthtribe2midi_Darwin_arm64.tar.gz"
      sha256 "14291bccdc765a02fcac2e9ee17234bf24eaa2e2c8e1fd6360513c3a765fb11f"

      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.0/synthtribe2midi_Linux_x86_64.tar.gz"
      sha256 "305cfd9bf86dd037c90b45d7a7dc90cb224f8929e6f0c9cfd104129943d18b68"
      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.0/synthtribe2midi_Linux_arm64.tar.gz"
      sha256 "c80879ff0ac6d1846c67e4fbac048606bb440d0bc7ee6551a18e32bc5636a817"
      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
  end

  test do
    system "#{bin}/synthtribe2midi", "--version"
  end
end
