# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synthtribe2midi < Formula
  desc "Convert between MIDI and Behringer SynthTribe formats"
  homepage "https://james-see.github.io/synthtribe2midi"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.3/synthtribe2midi_Darwin_x86_64.tar.gz"
      sha256 "4ac96edd06475b21c9e8ba7d34578e70cc99bb833d2ac25274729cf9fdfb20be"

      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.3/synthtribe2midi_Darwin_arm64.tar.gz"
      sha256 "ee4a746dd5ab6dd42d5372822c4bf13c2e38d661b12f24436698fd735688044a"

      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.3/synthtribe2midi_Linux_x86_64.tar.gz"
      sha256 "12dd39794436e6fac726253ef0ea45e2fb0d9bcc06f2ebb39fd3ebb8abe7e04f"
      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/synthtribe2midi/releases/download/v0.1.3/synthtribe2midi_Linux_arm64.tar.gz"
      sha256 "e9f9670e6a0919f4404de0199367398118f1c4f3545e71733837c95a72fb5a6e"
      def install
        bin.install "synthtribe2midi"
        bin.install "synthtribe2midi-server"
      end
    end
  end

  test do
    system "#{bin}/synthtribe2midi", "--version"
  end
end
