# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weatherornot < Formula
  desc "A beautiful weather CLI tool with ASCII art and charts"
  homepage "https://james-see.github.io/weatherornot/"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/james-see/weatherornot/releases/download/v1.0.1/weatherornot_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "09856a50a3e450c6c281806520ea3cd471602c460e64fee77dd2179dfc844b79"

      def install
        bin.install "weatherornot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/james-see/weatherornot/releases/download/v1.0.1/weatherornot_1.0.1_Darwin_arm64.tar.gz"
      sha256 "95f9c820943eec2f3c9cf137c45a847f0bd52964a782c7d55c831e6cb78d7aa6"

      def install
        bin.install "weatherornot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/weatherornot/releases/download/v1.0.1/weatherornot_1.0.1_Linux_x86_64.tar.gz"
      sha256 "261687d7f6c4b3dfb70629802a04a46d6de8960971c0c3fe2ce73c2f48591fc8"
      def install
        bin.install "weatherornot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-see/weatherornot/releases/download/v1.0.1/weatherornot_1.0.1_Linux_arm64.tar.gz"
      sha256 "b356e63314abaa210f56d79ceaee34bc1d87ee40519dfb4e0362a8f68bc3f9fb"
      def install
        bin.install "weatherornot"
      end
    end
  end

  test do
    system "#{bin}/weatherornot", "--help"
  end
end
